/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package userinterface.PurchasingRole;

import Business.Enterprise.CVSEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Order.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PurchaseWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Kaushik/Bo
 */
public class BrowseProductsJPanel extends javax.swing.JPanel {
    private JPanel upc;
    private SupplierEnterprise supplier;
    private UserAccount userAccount;
    private Order order;
    private CVSEnterprise enterprise;
    private boolean isCheckout = false;
    private double totalPrice;
    
    /** Creates new form BrowseProducts */
    public BrowseProductsJPanel(JPanel upc, SupplierEnterprise supplier, UserAccount userAccount, CVSEnterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.supplier = supplier;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        populateTable();
        if(!isCheckout){
            totalPrice = 0;
            order = new Order();
        }
            
        refreshOrderTable();
        
    }
    
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        model.setRowCount(0);
        
        for(Product p : supplier.getProductCatalog().getProductList()) {
            Object row[] = new Object[5];
            row[0] = p;
            row[1] = p.getModelNumber();
            row[2] = p.getPrice();
            row[3] = p.getAvail();
            row[4] = p.getProductType();
            model.addRow(row);
        }
    }
    
    
    public void refreshOrderTable()
    {
        DefaultTableModel model = (DefaultTableModel)orderTable.getModel();
        model.setRowCount(0);
        totalPrice = 0;
        for(OrderItem oi: order.getOrderItemList())
        {
            Object row[] = new Object[5];
            row[0] = oi;
            row[2] = oi.getQuantity();
            row[1] = oi.getProduct().getPrice();
            row[3] = oi.getQuantity()*oi.getProduct().getPrice();
            row[4] = oi.getProduct().getProductType();
            model.addRow(row);
            totalPrice += oi.getQuantity()*oi.getProduct().getPrice();
            
        }
        txtTotalPrice.setText(String.valueOf(totalPrice));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        viewProdjButton2 = new javax.swing.JButton();
        addtoCartButton6 = new javax.swing.JButton();
        quantitySpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSalesPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        btnRemoveOrderItem = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(750, 511));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productTable.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Product Id", "Price", "Avail", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.setRowHeight(24);
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
            productTable.getColumnModel().getColumn(2).setResizable(false);
            productTable.getColumnModel().getColumn(3).setResizable(false);
            productTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 129, 700, 140));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel2.setText("Supplier Product Catalog");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 28, 414, -1));

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, 47));

        viewProdjButton2.setBackground(new java.awt.Color(0, 153, 153));
        viewProdjButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        viewProdjButton2.setText("View Product Detail");
        viewProdjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProdjButton2ActionPerformed(evt);
            }
        });
        add(viewProdjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 238, 41));

        addtoCartButton6.setBackground(new java.awt.Color(102, 255, 102));
        addtoCartButton6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        addtoCartButton6.setText("Add To Cart");
        addtoCartButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtoCartButton6ActionPerformed(evt);
            }
        });
        add(addtoCartButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 160, 38));

        quantitySpinner.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(quantitySpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 154, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 97, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Sales Price :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 288, -1, -1));

        txtSalesPrice.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        add(txtSalesPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 280, 98, 35));

        jLabel7.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel7.setText("Items in Cart");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 206, -1));

        orderTable.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Price", "Quantity", "Total Amount", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setRowHeight(24);
        jScrollPane2.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
            orderTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 690, 122));

        btnRemoveOrderItem.setBackground(new java.awt.Color(0, 153, 153));
        btnRemoveOrderItem.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnRemoveOrderItem.setText("Remove from Cart");
        btnRemoveOrderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOrderItemActionPerformed(evt);
            }
        });
        add(btnRemoveOrderItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 247, 44));

        btnCheckOut.setBackground(new java.awt.Color(255, 102, 0));
        btnCheckOut.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCheckOut.setText("Check out>>");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 150, 45));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("$");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, -1, -1));

        txtTotalPrice.setEditable(false);
        txtTotalPrice.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        add(txtTotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 131, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Total Cost :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if(!order.getOrderItemList().isEmpty()){
            for(OrderItem oi : order.getOrderItemList())
            {
                
                int oldAvail = oi.getProduct().getAvail();
                int newAvail = oldAvail + oi.getQuantity();
                oi.getProduct().setAvail(newAvail);
            }
        }
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void viewProdjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProdjButton2ActionPerformed
        // TODO add your handling code here:
        int row = productTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        Product p = (Product)productTable.getValueAt(row, 0);
        ViewProductDetailJPanel vpdjp = new ViewProductDetailJPanel(upc, p);
        upc.add("ViewProductDetailJPanelCust", vpdjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
        
    }//GEN-LAST:event_viewProdjButton2ActionPerformed

    private void addtoCartButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtoCartButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = productTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Product p = (Product)productTable.getValueAt(selectedRow, 0);
        int fetchQty = (Integer)quantitySpinner.getValue();
        if(fetchQty <= 0)
        {
            JOptionPane.showMessageDialog(null, "Quantity cannot be less than or equal to 0!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try{
            double salesPrice = Double.parseDouble(txtSalesPrice.getText());
            if(salesPrice <= p.getPrice())
            {
                JOptionPane.showMessageDialog(null, "Quantity cannot be less than or equal to 0!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(fetchQty <= p.getAvail())
            {
                boolean alreadyPresent = false;
                for(OrderItem oi : order.getOrderItemList())
                {
                    if(oi.getProduct() == p)
                    {
                        int oldAvail = p.getAvail();
                        int newAvail = oldAvail - fetchQty;
                        p.setAvail(newAvail);
                        oi.setQuantity(fetchQty + oi.getQuantity());
                        alreadyPresent = true;
                        populateTable();
                        refreshOrderTable();
                    }
                }
                if(!alreadyPresent)
                {
                    int oldAvail = p.getAvail();
                    int newAvail = oldAvail - fetchQty;
                    p.setAvail(newAvail);
                    order.addOrderItem(p, fetchQty, salesPrice);
                    populateTable();
                    refreshOrderTable();
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Quantity is greater than availability", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "invalid price!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       
    }//GEN-LAST:event_addtoCartButton6ActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        if(!order.getOrderItemList().isEmpty())
        {
            PurchaseWorkRequest request = new PurchaseWorkRequest();
            enterprise.getOrderDirectory().addOrder(order);
            order.setStatus("Placed");
            request.setOrder(order); 
            request.setSender(userAccount);
            //request.setStatus("Order placed");
            request.getOrder().setEnterprise(enterprise);
            request.setStatus("Pending");
            userAccount.getSendWorkQueue().getWorkRequestList().add(request);
            supplier.getPurchasingWorkQueue().getWorkRequestList().add(request);
            
            JOptionPane.showMessageDialog(null, "Order placed successfully!");
            order = new Order();
            populateTable();
            refreshOrderTable();
            isCheckout = true;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No order placed!", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
       
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnRemoveOrderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOrderItemActionPerformed
        int row = orderTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        OrderItem p = (OrderItem)orderTable.getValueAt(row, 0);
        int oldAvail = p.getProduct().getAvail();
        int oldQty = p.getQuantity();
        int newQty = oldAvail + oldQty;
        p.getProduct().setAvail(newQty);
        order.removeOrderItem(p);
        JOptionPane.showMessageDialog(null, "Order item removed from cart!");
        
        populateTable();
        refreshOrderTable();   
        
    }//GEN-LAST:event_btnRemoveOrderItemActionPerformed

                                           

//    private void btnRemoveOrderItemActionPerformed(java.awt.event.ActionEvent evt) {                                                   
//        int row = productTable.getSelectedRow();
//        if(row<0){
//            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
//        }
//        OrderItem p = (OrderItem)orderTable.getValueAt(row, 0);
//        int oldAvail = p.getProduct().getAvail();
//        int oldQty = p.getQuantity();
//        int newQty = oldAvail + oldQty;
//        p.getProduct().setAvail(newQty);
//        order.removeOrderItem(p);
//        JOptionPane.showMessageDialog(null, "Order item removed from cart!");
//        
//        populateTable();
//        refreshOrderTable();   
//        
//    }                                                  

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtoCartButton6;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnRemoveOrderItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable productTable;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JTextField txtSalesPrice;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JButton viewProdjButton2;
    // End of variables declaration//GEN-END:variables
}
