/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ManagerRole;


import Business.Enterprise.Enterprise;
import Business.Enterprise.CVSEnterprise;
import Business.Order.Order;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kaushik
 */
public class CVSOrdersJPanel extends javax.swing.JPanel {
    private JPanel upc;
    private CVSEnterprise enterprise;
    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CVSOrdersJPanel(JPanel upc, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.enterprise = (CVSEnterprise)enterprise;
        populateOrderTable();
    }
    
    public void populateOrderTable()
    {
        DefaultTableModel model = (DefaultTableModel)orderTable.getModel();
        model.setRowCount(0);
        
        for(Order o: enterprise.getOrderDirectory().getOrderDirectory()){
            Object row[] = new Object[4];
            row[0] = o;
            row[1] = String.valueOf(o.getOrderNumber());
            row[2] = String.valueOf(o.getTotalPrice());
            row[3] = o.getStatus();
            model.addRow(row);            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBrowsePro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Orders :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 138, 134, 45));

        btnBrowsePro.setBackground(new java.awt.Color(0, 153, 153));
        btnBrowsePro.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBrowsePro.setText("View Orders>>");
        btnBrowsePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseProActionPerformed(evt);
            }
        });
        add(btnBrowsePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, 45));

        orderTable.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order", "Order Number", "Total Price", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderTable.setRowHeight(24);
        jScrollPane2.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 189, 760, 167));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 50));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel2.setText("View Orders");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 78, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseProActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Pls select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Order order = (Order)orderTable.getValueAt(selectedRow, 0);
        ViewCVSOrderJPanel browse = new ViewCVSOrderJPanel(order, upc);
        upc.add("BuyProductsJPanel", browse);
        CardLayout layout = (CardLayout)upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_btnBrowseProActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowsePro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    // End of variables declaration//GEN-END:variables
}
